#!/usr/bin/env bash
# File: 1-install_load_balancer

# Define IP addresses for the backend servers.
WEB_01_IP="54.88.121.204"
WEB_02_IP="52.87.157.15"

# 1. Update package lists and install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# 2. Configure HAproxy
CONFIG_CONTENT=$(cat <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 ${WEB_01_IP}:80 check
    server web02 ${WEB_02_IP}:80 check
EOF
)

echo "$CONFIG_CONTENT" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# 3. Enable HAproxy startup at boot and restart service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy restart
