#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a 301 status code

# Install nginx if not installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Add redirection rule if not already present
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
fi

# Restart nginx to apply the configuration
sudo systemctl restart nginx
